# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.twig_extension.substr_count_extension:
        class: AppBundle\Twig\SubStrCountExtension
        tags:
            - { name: twig.extension }

    app.twig_extension.compara_hora_extension:
        class: AppBundle\Twig\ComparaHoraExtension
        tags:
            - { name: twig.extension }        